name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: "14"

      - name: install dependencies
        run: yarn install

      - name: check types
        run: ./node_modules/.bin/tsc

      - name: run test
        run: ./node_modules/.bin/jest
